### ISSUE TITLE
class_loader/register_macro.hpp error

### ISSUE THREAD

**Issue by plusangel** [ros2/examples#207] opened 2018-05-26 20:06 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  -  binaries or from source 
- Version or commit hash:
  - ardent
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  -  rclcpp

#### Steps to reproduce the issue
I have installed ROS2 ardent from binaries and I tried to ament build the examples.
The build was always failed to return the following error:

/home/angelos/ros2_overlay_ws/src/examples/rclcpp/minimal_composition/src/publisher_node.cpp:39:43: fatal error: class_loader/register_macro.hpp: No such file or directory
compilation terminated.
CMakeFiles/composition_nodes.dir/build.make:62: recipe for target 'CMakeFiles/composition_nodes.dir/src/publisher_node.cpp.o' failed
make[2]: *** [CMakeFiles/composition_nodes.dir/src/publisher_node.cpp.o] Error 1
/home/angelos/ros2_overlay_ws/src/examples/rclcpp/minimal_composition/src/subscriber_node.cpp:29:43: fatal error: class_loader/register_macro.hpp: No such file or directory

By searching deeper in my ROS2 installation I discovered that the correct header files are:
class_loader/class_loader_register_macro.h

Then everything works as expected.

**Comment by mikaelarguedas** [comment] 2018-05-28 13:14
Thanks @plusangel for reporting this.

ROS doesnt ensure compatibility between releases, this is even more true for ROS2 as it is under active development.

If you base your system on ROS Ardent, you should use the `ardent` version of the repositories you want to compile from source. There is a `ros2.repos` file for each release, you can use the [`release-latest` one](https://github.com/ros2/ros2/blob/release-latest/ros2.repos) to get the repository versions used for the last release.

If you want to use the current state of the code, we recommend building everything from source using the [ros2.repos file from the master branch](https://github.com/ros2/ros2/blob/master/ros2.repos) or use [our nightly builds](https://ci.ros2.org/view/packaging/job/packaging_linux/lastSuccessfulBuild/artifact/).

HTH,

As this is not a bug in the code but due to a version mismatch, I'm going to close this issue.

**Closed by mikaelarguedas** 2018-05-28 13:14 UTC
