### ISSUE TITLE
Cannot build (rclcpp) example using crystal branch 

### ISSUE THREAD

**Issue by miguelvelezmj25** [ros2/examples#233] opened 2019-03-28 17:56 UTC
## Bug report

**Required Info:**

- Operating System: 
  -  Ubuntu 18.04.2 LTS
- Installation type:
  -  binaries
- Version or commit hash:
  -  Crystal (HEAD)
- DDS implementation:
  -  FastRTPS

#### Steps to reproduce issue

```
1. Fresh binary install of ROS2 Crystal
2. Fresh binary install of ROS1 Melodic
3. Fresh install ros1-bridge
4. Fresh install rosbag2
5. Follow instructions of [Using Colcon to build packages](https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/)
6. Create workspace
7. Clone repo
8. Build
```

#### Expected behavior

Built workspace

#### Actual behavior

```
mvelezce@config-crusher:~/Documents/programming/ros2/projects/ros2_example_ws$ colcon build --symlink-install
Starting >>> examples_rclcpp_minimal_action_client
Starting >>> examples_rclcpp_minimal_action_server
Starting >>> examples_rclcpp_minimal_client
Starting >>> examples_rclcpp_minimal_composition
Starting >>> examples_rclcpp_minimal_publisher
Starting >>> examples_rclcpp_minimal_service
Starting >>> examples_rclcpp_minimal_subscriber
Starting >>> examples_rclcpp_minimal_timer
--- stderr: examples_rclcpp_minimal_timer                                                                                                                                                                 
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [timer_lambda] Error 1
make[1]: *** [CMakeFiles/timer_lambda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [timer_member_function] Error 1
make[1]: *** [CMakeFiles/timer_member_function.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< examples_rclcpp_minimal_timer	[ Exited with code 2 ]
--- stderr: examples_rclcpp_minimal_service                                                                                                                                                                          
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [service_main] Error 1
make[1]: *** [CMakeFiles/service_main.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_service
--- stderr: examples_rclcpp_minimal_client                                                                                                                                                                            
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [client_main] Error 1
make[1]: *** [CMakeFiles/client_main.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_client
--- stderr: examples_rclcpp_minimal_publisher                                                                                                                                                                              
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [publisher_lambda] Error 1
make[1]: *** [CMakeFiles/publisher_lambda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [publisher_member_function] Error 1
make[1]: *** [CMakeFiles/publisher_member_function.dir/all] Error 2
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [publisher_not_composable] Error 1
make[1]: *** [CMakeFiles/publisher_not_composable.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_publisher
--- stderr: examples_rclcpp_minimal_action_server                                                                                                                                                                           
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [action_server_not_composable] Error 1
make[1]: *** [CMakeFiles/action_server_not_composable.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_action_server
--- stderr: examples_rclcpp_minimal_subscriber                                                                                                                                                                          
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [subscriber_member_function] Error 1
make[1]: *** [CMakeFiles/subscriber_member_function.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [subscriber_not_composable] Error 1
make[1]: *** [CMakeFiles/subscriber_not_composable.dir/all] Error 2
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [subscriber_lambda] Error 1
make[1]: *** [CMakeFiles/subscriber_lambda.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_subscriber
--- stderr: examples_rclcpp_minimal_action_client                                                                                                                
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [action_client_not_composable_with_cancel] Error 1
make[1]: *** [CMakeFiles/action_client_not_composable_with_cancel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [action_client_not_composable_with_feedback] Error 1
make[1]: *** [CMakeFiles/action_client_not_composable_with_feedback.dir/all] Error 2
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [action_client_not_composable] Error 1
make[1]: *** [CMakeFiles/action_client_not_composable.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_action_client
--- stderr: examples_rclcpp_minimal_composition                                            
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [composition_subscriber] Error 1
make[1]: *** [CMakeFiles/composition_subscriber.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [composition_composed] Error 1
make[1]: *** [CMakeFiles/composition_composed.dir/all] Error 2
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/opt/ros/crystal/lib/librclcpp.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
make[2]: *** [composition_publisher] Error 1
make[1]: *** [CMakeFiles/composition_publisher.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< examples_rclcpp_minimal_composition

Summary: 0 packages finished [11.9s]
  1 package failed: examples_rclcpp_minimal_timer
  7 packages aborted: examples_rclcpp_minimal_action_client examples_rclcpp_minimal_action_server examples_rclcpp_minimal_client examples_rclcpp_minimal_composition examples_rclcpp_minimal_publisher examples_rclcpp_minimal_service examples_rclcpp_minimal_subscriber
  8 packages had stderr output: examples_rclcpp_minimal_action_client examples_rclcpp_minimal_action_server examples_rclcpp_minimal_client examples_rclcpp_minimal_composition examples_rclcpp_minimal_publisher examples_rclcpp_minimal_service examples_rclcpp_minimal_subscriber examples_rclcpp_minimal_timer
  7 packages not processed
```

#### Additional information
Removing ```rclcpp``` directory builds the workspace without any issues.

```
mvelezce@config-crusher:~/Documents/programming/ros2/projects/ros2_example_ws$ colcon build --symlink-install
Starting >>> examples_rclpy_executors
Starting >>> examples_rclpy_minimal_action_client
Starting >>> examples_rclpy_minimal_action_server
Starting >>> examples_rclpy_minimal_client
Starting >>> examples_rclpy_minimal_publisher
Starting >>> examples_rclpy_minimal_service
Starting >>> examples_rclpy_minimal_subscriber
Finished <<< examples_rclpy_executors [2.21s]                                                                                                                                                             
Finished <<< examples_rclpy_minimal_action_client [2.16s]                                                                                                                                                         
Finished <<< examples_rclpy_minimal_action_server [2.16s]
Finished <<< examples_rclpy_minimal_client [2.16s]
Finished <<< examples_rclpy_minimal_publisher [2.17s]
Finished <<< examples_rclpy_minimal_service [2.17s]
Finished <<< examples_rclpy_minimal_subscriber [2.44s]          

Summary: 7 packages finished [2.70s]
```

**Comment by nuclearsandwich** [comment] 2019-03-28 18:21
@miguelvelezmj25 did you check out the `crystal` branch as suggested in the tutorial?

**Comment by miguelvelezmj25** [comment] 2019-03-28 18:25
@nuclearsandwich Yes, I did.

```
mvelezce@config-crusher:~/Documents/programming/ros2/projects/ros2_example_ws/src/examples$ git status
On branch crystal
Your branch is up to date with 'origin/crystal'.

nothing to commit, working tree clean
```

**Comment by wjwwood** [comment] 2019-03-28 18:30
It looks like you might be mixing clang and gcc or different versions of the one of them. Are you using the default compiler in 18.04 that our binaries were built with?

**Comment by nuclearsandwich** [comment] 2019-03-28 18:42
>> did you check out the crystal branch as suggested in the tutorial?
> Yes, I did.

Thanks for confirming. I wasn't able to reproduce your error on on 18.04 using the latest Crystal debs and the crystal branch of ros2/examples.

In addition to @wjwwood's questions above, can you please share more about your environment.

**Comment by miguelvelezmj25** [comment] 2019-03-28 18:45
Yes, you were right. It was using the homebrew gcc

```
mvelezce@config-crusher:~$ gcc --version
gcc (Homebrew gcc 5.5.0_4) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

instead of the default compiler. 

```
mvelezce@config-crusher:~$ /usr/bin/gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I just removed the homebrew compiler and it worked as expected. Thank you!

**Comment by wjwwood** [comment] 2019-03-28 18:47
I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.

**Comment by dirk-thomas** [comment] 2019-03-28 18:47
@miguelvelezmj25 If your question / problem has been resolved please go ahead and close the ticket.

**Closed by wjwwood** 2019-03-28 18:47 UTC

**Comment by shanpenghui** [comment] 2019-06-04 10:00
After checkout the crystal branch compile successfully.
